// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/access-denied" | "/go/[slug]" | "/privacy-policy" | "/sign-in/[[...sign-in]]" | "/site/help" | "/site/link-manager" | "/site/privacy" | "/site/status" | "/site/support" | "/site/terms" | "/site/users" | "/terms-of-service"
type AppRouteHandlerRoutes = "/api/admin/policies" | "/api/admin/qr-requests" | "/api/admin/settings" | "/api/admin/users" | "/api/admin/users/[id]" | "/api/link-folders" | "/api/link-folders/[id]" | "/api/link-folders/reorder" | "/api/links" | "/api/links/[id]" | "/api/qr-code/request" | "/api/redirect/[slug]" | "/api/reports" | "/api/reports/[id]" | "/api/reports/[id]/comments" | "/api/search" | "/api/submissions/count"
type PageRoutes = never
type LayoutRoutes = "/" | "/sign-in/[[...sign-in]]" | "/site/link-manager" | "/site/status" | "/site/support" | "/site/users"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/access-denied": {}
  "/api/admin/policies": {}
  "/api/admin/qr-requests": {}
  "/api/admin/settings": {}
  "/api/admin/users": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/link-folders": {}
  "/api/link-folders/[id]": { "id": string; }
  "/api/link-folders/reorder": {}
  "/api/links": {}
  "/api/links/[id]": { "id": string; }
  "/api/qr-code/request": {}
  "/api/redirect/[slug]": { "slug": string; }
  "/api/reports": {}
  "/api/reports/[id]": { "id": string; }
  "/api/reports/[id]/comments": { "id": string; }
  "/api/search": {}
  "/api/submissions/count": {}
  "/go/[slug]": { "slug": string; }
  "/privacy-policy": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/site/help": {}
  "/site/link-manager": {}
  "/site/privacy": {}
  "/site/status": {}
  "/site/support": {}
  "/site/terms": {}
  "/site/users": {}
  "/terms-of-service": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/sign-in/[[...sign-in]]": never
  "/site/link-manager": never
  "/site/status": never
  "/site/support": never
  "/site/users": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
