// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/help">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/link-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/link-manager">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/link-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/privacy">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/status">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/support">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/terms">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/users">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../app/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/access-denied/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access-denied">> = Specific
  const handler = {} as typeof import("../../app/access-denied/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/go/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/go/[slug]">> = Specific
  const handler = {} as typeof import("../../app/go/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/policies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/policies">> = Specific
  const handler = {} as typeof import("../../app/api/admin/policies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/qr-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qr-requests">> = Specific
  const handler = {} as typeof import("../../app/api/admin/qr-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/link-folders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/link-folders/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/link-folders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/link-folders/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/link-folders/reorder">> = Specific
  const handler = {} as typeof import("../../app/api/link-folders/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/link-folders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/link-folders">> = Specific
  const handler = {} as typeof import("../../app/api/link-folders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/links/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/links/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/links/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/links">> = Specific
  const handler = {} as typeof import("../../app/api/links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/qr-code/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qr-code/request">> = Specific
  const handler = {} as typeof import("../../app/api/qr-code/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/redirect/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/redirect/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/redirect/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/[id]/comments">> = Specific
  const handler = {} as typeof import("../../app/api/reports/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/reports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/submissions/count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submissions/count">> = Specific
  const handler = {} as typeof import("../../app/api/submissions/count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/link-manager/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/site/link-manager">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/link-manager/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/status/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/site/status">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/status/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/support/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/site/support">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/support/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/site/users/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/site/users">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/site/users/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-in/[[...sign-in]]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../app/sign-in/[[...sign-in]]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
